// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK9PofHYqv5TBjMyz72Wx0Dw5OLGrvXjM',
    appId: '1:869099138486:web:48d98d9536d41e57f0a517',
    messagingSenderId: '869099138486',
    projectId: 'pbase-peminjaman-alat-lab',
    authDomain: 'pbase-peminjaman-alat-lab.firebaseapp.com',
    storageBucket: 'pbase-peminjaman-alat-lab.firebasestorage.app',
    measurementId: 'G-J4GF8NGVGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC3ua3anbkvoUYCn3PxsMeg7Yv4mOVQO0',
    appId: '1:869099138486:android:e39259c7191ff34cf0a517',
    messagingSenderId: '869099138486',
    projectId: 'pbase-peminjaman-alat-lab',
    storageBucket: 'pbase-peminjaman-alat-lab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRY3UE6XdwhHbvPcPaW85Z3EdXRFoiTQA',
    appId: '1:869099138486:ios:44c5038687450570f0a517',
    messagingSenderId: '869099138486',
    projectId: 'pbase-peminjaman-alat-lab',
    storageBucket: 'pbase-peminjaman-alat-lab.firebasestorage.app',
    iosBundleId: 'com.example.pbasePeminjamanAlatLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRY3UE6XdwhHbvPcPaW85Z3EdXRFoiTQA',
    appId: '1:869099138486:ios:44c5038687450570f0a517',
    messagingSenderId: '869099138486',
    projectId: 'pbase-peminjaman-alat-lab',
    storageBucket: 'pbase-peminjaman-alat-lab.firebasestorage.app',
    iosBundleId: 'com.example.pbasePeminjamanAlatLab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK9PofHYqv5TBjMyz72Wx0Dw5OLGrvXjM',
    appId: '1:869099138486:web:7a9b932c78b22ecdf0a517',
    messagingSenderId: '869099138486',
    projectId: 'pbase-peminjaman-alat-lab',
    authDomain: 'pbase-peminjaman-alat-lab.firebaseapp.com',
    storageBucket: 'pbase-peminjaman-alat-lab.firebasestorage.app',
    measurementId: 'G-WF7J51H0YE',
  );
}
